apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyetech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyetech
  template:
    metadata:
      labels:
        app: cyetech
    spec:
      containers:
      - name: cyetech
        image: 145023139102.dkr.ecr.ap-south-1.amazonaws.com/cyetechnology
        ports:
        - containerPort: 8080
